# Generated by Django 4.2.5 on 2023-09-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightrecord",
            name="alt_baro",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
