# Generated by Django 4.2.5 on 2023-09-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_flightrecord_gs_alter_flightrecord_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('zoom', models.IntegerField()),
            ],
        ),
    ]
