# Generated by Django 4.2.5 on 2023-09-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cameraposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameraposition',
            old_name='lon',
            new_name='lng',
        ),
    ]
