# Generated by Django 4.2.5 on 2023-09-28 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_lon_cameraposition_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightrecord',
            old_name='lon',
            new_name='lng',
        ),
        migrations.CreateModel(
            name='FlightMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
            ],
        ),
    ]
