# Generated by Django 4.2.5 on 2023-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightmarker',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
