# Generated by Django 4.2.5 on 2023-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_flightmarker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='ident',
            field=models.CharField(default='temp', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='type',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
