# Generated by Django 4.2.5 on 2023-10-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_cameraposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
