# Generated by Django 4.2.5 on 2023-10-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_marker_initialized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='initialized',
            new_name='onMap',
        ),
        migrations.AddField(
            model_name='marker',
            name='flyTo',
            field=models.BooleanField(default=False),
        ),
    ]
