# Generated by Django 4.2.5 on 2023-10-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_initialized_marker_onmap_marker_flyto'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='toRemove',
            field=models.BooleanField(default=False),
        ),
    ]
