# Generated by Django 4.2.5 on 2023-10-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_marker_toremove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.airport'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.flight'),
        ),
    ]
