# Generated by Django 4.2.5 on 2023-10-14 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_marker_airport_alter_marker_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polyline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onMap', models.BooleanField()),
                ('toRemove', models.BooleanField()),
                ('mark_aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Aircraft', to='api.marker')),
                ('mark_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Airport', to='api.marker')),
            ],
        ),
    ]
