# Generated by Django 4.2.5 on 2023-10-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_polyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polyline',
            name='onMap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='polyline',
            name='toRemove',
            field=models.BooleanField(default=False),
        ),
    ]
