# Generated by Django 4.2.5 on 2023-10-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_polyline_onmap_alter_polyline_toremove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyline',
            name='mark_aircraft',
        ),
        migrations.RemoveField(
            model_name='polyline',
            name='mark_airport',
        ),
        migrations.AddField(
            model_name='polyline',
            name='aircraftID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='polyline',
            name='airportID',
            field=models.IntegerField(null=True),
        ),
    ]
