# Generated by Django 4.1 on 2023-10-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_polyline_mark_aircraft_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polyline',
            old_name='airportID',
            new_name='airportIDFrom',
        ),
        migrations.AddField(
            model_name='polyline',
            name='airportIDTo',
            field=models.IntegerField(null=True),
        ),
    ]
