# Generated by Django 4.2.5 on 2023-10-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_airportid_polyline_airportidfrom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polyline',
            old_name='airportIDFrom',
            new_name='airportID',
        ),
        migrations.RemoveField(
            model_name='polyline',
            name='airportIDTo',
        ),
    ]
