# Generated by Django 4.2.5 on 2023-10-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_airportidfrom_polyline_airportid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polyline',
            old_name='airportID',
            new_name='airportIDFrom',
        ),
        migrations.AddField(
            model_name='polyline',
            name='airportIDTo',
            field=models.IntegerField(null=True),
        ),
    ]
