# Generated by Django 4.2.5 on 2023-10-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_airportid_polyline_airportidfrom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='ident',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='flightrecord',
            old_name='gs',
            new_name='ground_speed',
        ),
    ]
