# Generated by Django 4.2.5 on 2023-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_ident_airport_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='flightrecord',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
