# Generated by Django 4.2.5 on 2023-11-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_ident_airport_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='t',
            new_name='aircraft_type',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='r',
            new_name='registration',
        ),
    ]
