# Generated by Django 4.2.5 on 2023-11-13 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_ident_airport_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='t',
            new_name='aircraftType',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='r',
            new_name='registration',
        ),
        migrations.AddField(
            model_name='airport',
            name='nameAbbreviated',
            field=models.CharField(default='airport', max_length=20),
        ),
        migrations.AddField(
            model_name='airport',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='airportDestination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='api.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airportOrigin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to='api.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='alt_baro',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='alt_geom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ground_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flight',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flight',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='totalDistance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='track',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('hex', 'timestamp')},
        ),
        migrations.DeleteModel(
            name='FlightRecord',
        ),
    ]
