# Generated by Django 4.2.5 on 2023-11-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_marker_rotation_alter_flightrecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrecord',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
