# Generated by Django 4.2.5 on 2023-11-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_flightrecord_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
