# Generated by Django 4.2.5 on 2023-11-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_airport_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='type',
            new_name='airportType',
        ),
    ]
