# Generated by Django 4.2.5 on 2023-11-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_type_airport_airporttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('alt_baro', models.IntegerField(blank=True, null=True)),
                ('alt_geom', models.IntegerField(blank=True, null=True)),
                ('track', models.FloatField(blank=True, null=True)),
                ('ground_speed', models.FloatField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.flight')),
            ],
            options={
                'unique_together': {('flight', 'timestamp')},
            },
        ),
    ]
