# Generated by Django 4.2.5 on 2023-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_flightrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='estimatedTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='remaining',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='travaled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
