# Generated by Django 4.2.5 on 2023-12-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_landmark_remove_marker_onmap_remove_marker_toremove_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyline',
            name='onMap',
        ),
        migrations.RemoveField(
            model_name='polyline',
            name='toRemove',
        ),
    ]
