# Generated by Django 4.2.5 on 2023-12-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_polyline_onmap_remove_polyline_toremove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraftType',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='registration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
