# Generated by Django 4.2.5 on 2023-12-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_flight_aircrafttype_alter_flight_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airportType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='nameAbbreviated',
            field=models.CharField(default='airport', max_length=20, null=True),
        ),
    ]
