# Generated by Django 4.2.5 on 2023-12-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_polyline_aircraftid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
